### ISSUE TITLE
Running the example basicTest doesn't work even though everything is connected properly

### ISSUE THREAD

**Issue by jolanda300** [Infineon/multi-half-bridge#11]
I've followed every step (including hooking everything up) as shown by your youtube video. Running basicTest doesn't work, the 12V power supply powers the board. Too bad... quick fix I hope?

**Comment by ederjc** [comment]
Hi jolanda300,

I assume you are using the [TLE94112 HAT](https://www.infineon.com/raspTLE94112ES) on a Raspberry Pi board?

- Which Raspberry Pi are you using?
- Which operating system?
- Which load did you connect to the HAT?

Have you tried the [errorDiagnosis](https://github.com/Infineon/multi-half-bridge/wiki/RPi-Examples#errordiagnosis) example?
What's the output of this example?

Thanks,
Julian

**Comment by jolanda300** [comment]
Hi Julian,

That is correct.

- Raspberry Pi 3B+
- Ubuntu Server 20.04.3 LTS 
- [DC Motor](https://www.kiwi-electronics.nl/image/cache/catalog/product/4be8dd9c/KW-2628_0-1280x853h.jpg) (tested it by directly connecting it to 12V source and it rotates, afterwards connected it to "1" and "5")

Will try the errorDiagnosis.

Thank you,
Jolanda

**Comment by jolanda300** [comment]
The raspberry is booted via the 12V power supply and I get the following:

Motor active, starting loop.

SPI error detected!
Over voltage detected!
Power on reset detected!

---
Everything is connected fine and even the raspberry boots from the 12V supply, DC motor works as well. What seems to be the problem?

**Comment by ederjc** [comment]
Hi Jolanda,

thanks for the quick feedback :)

The `errorDiagnosis` runs in a loop and reads the error registers every 5 seconds. Do these errors persist when the loop runs multiple times?

Which DC motor are you using?

Regards,
Julian

**Comment by jolanda300** [comment]
Hi Julian,

The errors persist (I stopped it after 10 times). It is a cheap yellow dc motor that I'm using:
https://nl.farnell.com/productimages/large/en_GB/MC02751-40.jpg


Regards,
Jolanda

**Comment by jolanda300** [comment]
Is SPI by default enabled with Ubuntu Server?

**Comment by ederjc** [comment]
This could indeed be an issue with your SPI setup.

For [Raspberry Pi OS](https://www.raspberrypi.org/software/) SPI is enabled automatically when the HAT is connected to the Raspberry Pi during boot.
I am not sure if this works for Ubuntu Server as well, because we are using Raspberry Pi OS on our Pis.

It looks like you have to enable SPI manually when using Ubuntu, maybe [this](https://askubuntu.com/questions/1340547/enable-spi-on-ubuntu-20-04-for-raspberry-pi) helps? I didn't test the linked tutorial, so please be aware that you are acting on your own risk ⚠️

**Comment by jolanda300** [comment]
Hi Julian,

I've downloaded Raspbian OS 32-bit and I've enabled SPI via raspi-config.

This time I've powered the RPi via a separate 5V 3A power supply and I powered the DC motor/the tle hat via a 12V adapter.

I've ran the basicTest example and it didn't spin. What I did notice was, I was holding the DC motor in my hand, and everytime I ran the basicTest example I felt shortly something, it is like the DC motor wants to start but can't (how to explain, like a hickup). 

Regards,
Jolanda

**Comment by ederjc** [comment]
Hi Jolanda,

good to hear that you got the SPI communication working :)

The TLE94112ES has a very fast (typ. 19μs ) overcurrent protection at 900mA per channel.
As you are running the motor with 12V, which is supposably a bit higher than the motor's rated voltage, there might be a very short overcurrent at motor start triggering the overcurrent protection.

There are multiple ways to prevent this on hardware side:
- Use a lower voltage for this motor
- Parallel two or more outputs of the TLE94112ES HAT (up to four output channels can be parallelized to combine their current)
- Limit the starting current with external circuitry

...or on software side, by using the `rampSpeed` method for a slow motor start:
```
 // Slowly ramp up duty cycle from 0% to 100%.
 printf("- Slowly ramp up duty cycle from 0%% to 100%.\n");
 motor.rampSpeed(255, 20000);
 delay(DELAY);
```
Check out the [advancedTest](https://github.com/Infineon/multi-half-bridge/wiki/RPi-Examples#advancedtest) example for details.

I hope I could help you!

Julian

**Comment by jolanda300** [comment]
Hi Julian,

I've ran the advancedTest and at the section:

```
--- RAMP UP/DOWN MOTOR SPEED ---

- Slowly ramp up duty cycle from 0% to 100%.0

```
it would make a bit more noise but at the end it doesn't spin.

I will find a 5V supply and test it out and let you know, thank you for helping!

Regards,
Jolanda

**Comment by jolanda300** [comment]
Hi Julian,

It worked perfect with the 5V 2A adapter, thanks! 

Regards,
Jolanda
