### ISSUE TITLE
ModusToolbox Example Question

### ISSUE THREAD

**Issue by keenanjohnson** [Infineon/multi-half-bridge#13]
Hello! I see that [ModusToolbox is one of the frameworks in the PAL source](https://github.com/Infineon/multi-half-bridge/tree/master/src/framework/modustoolbox). However, I don't see how to reconcile the CMAKE build system of the tests, etc with the make build system of Modustoolbox. Is there an an example somewhere which shows the full instructions or build system to integrate this into a Modustoolbox project?

Thanks!

**Comment by jaenrig-ifx** [comment]
Hi @keenanjohnson,

The cmake workflow is supporting the unit testing, but it is not integrated in the ModusToolbox make system. Only run separately.
You can build multiple code examples of this library for PSoC6 using this code example -> https://github.com/Infineon/mtb-example-multi-half-bridge (which uses this library).

A new release of that example, migrated to the ModusToolbox 3.0 is planned in the upcoming week.s

**Comment by keenanjohnson** [comment]
Thanks @jaenrig-ifx ! That answers my question :).

If anyone at Infineon is wondering, I would definitely appreciate a future where cmake or some other more modern build system is supported officially by modustoolbox :)
